Mark/Controllers/CategoryController.cs
using Mark.Dao;
using Mark.Models;
using Microsoft.AspNetCore.Mvc;

namespace Mark.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Category> list = _db.categories;
            return View(list);
        }

        public IActionResult Create ()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj) 
        {
            if(ModelState.IsValid)
            {
                _db.categories.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id==0)
            {
                return NotFound();
            }
            var obj = _db.categories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.categories.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            _db.categories.Remove(_db.categories.Find(id));
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Mark/Controllers/ToyController.cs
using Mark.Dao;
using Mark.Models;
using Mark.Models.ModelViews;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Mark.Controllers
{
    public class ToyController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnviroment;

        public ToyController(ApplicationDbContext db, IWebHostEnvironment webHostEnviroment)
        {
            _db = db;
            _webHostEnviroment = webHostEnviroment; 
        }

        //Get 
        //Данная функция позволяет взять данные из базы данных
        public IActionResult Index()
        {
            //Берем из базы данных объекты Toy
            IEnumerable<Toy>? toys = _db.toys;
            foreach(var obj in toys)
            {
                //Каждому объекту подгружаем категорию ( так как в базе данных ссылается внешний ключ)
                obj.Category = _db.categories.FirstOrDefault(u => u.Id == obj.CategoryId);
            }
            //Передаем представлению, тоесть html странице данные что бы она их вывела
            return View(toys);
        }

        //Get
       
        public IActionResult Upsert(int? id)
        {
            ToyVM toyVM = new ToyVM()
            {
                //создаем обхект игрушки
                toy =new Toy(),
                //подгружаем категории
                categoryList = _db.categories.Select(i=>new SelectListItem
                {
                    Text=i.Name,
                    Value=i.Id.ToString()
                })
            };
            //Если такой игрушки нет, то выводим пользователю пустую формочку для ввода данных
            if (id == null)  
            {
             
                return View(toyVM);
            }
            else
            {
                //если такая игрушка есть, заполняем данные в форме
                toyVM.toy = _db.toys.Find(id);
                if(toyVM.toy== null)
                {
                    return NotFound();
                }
                //и выводим на страницу, для редактирования данных
                return View(toyVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ToyVM obj)
        {
            //Получаем фалй который передает пользователь в системк
            var files = HttpContext.Request.Form.Files;
            //получаем путь с помощью ссылки
            string webRootPath = _webHostEnviroment.WebRootPath;

            if (obj.toy.Id == 0)
            {
                //Получаем новый путь
                string upload = webRootPath + WC.ImagePath;
                //получаем иденфикатор файла
                string fileName = Guid.NewGuid().ToString();
                //берем имя
                string extnsion = Path.GetExtension(files[0].FileName);
                //создаем поток для файла
                using (var fileStream = new FileStream(Path.Combine(upload, fileName + extnsion), FileMode.Create))
                {
                    //копируем файл в этот поток 
                    files[0].CopyTo(fileStream);
                }
                //задаем файлу новый путь
                obj.toy.Image = fileName + extnsion;
                //добавляем изменения в базу данных
                _db.toys.Add(obj.toy);
                //сохраняем изменения
                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            //если пользователь редактирует данные
            else
            {
                //получаем объект из базы данных
                var objDB = _db.toys.AsNoTracking().FirstOrDefault(u => u.Id == obj.toy.Id);
                if (files.Count > 0)
                {
                    //путь загруженного файла
                    string upload = webRootPath + WC.ImagePath;
                    //берем иденфикатор файла
                    string fileName = Guid.NewGuid().ToString();
                    //берем файл загруженный
                    string extnsion = Path.GetExtension(files[0].FileName);
                    //находим старый путь файла
                    var oldImage = Path.Combine(upload, objDB.Image);
                    if(System.IO.File.Exists(oldImage))
                    {
                        //удаляем старый файл
                        System.IO.File.Delete(oldImage);
                    }
                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extnsion), FileMode.Create))
                    {
                        //добавляем вновь загруженный файл
                        files[0].CopyTo(fileStream);
                    }
                    obj.toy.Image= fileName + extnsion;

                }
                else
                {
                    //если пользователь не исправляет картинку у товара, то оставляем ее такой же
                    obj.toy.Image = objDB.Image;
                }
                //обновляем данные в базе данных
                _db.Update(obj.toy);
                //сохраняем данные
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

        }

        //public IActionResult Delete(int? id)
        //{
        //    if (id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Toy toy = _db.toys.Include(u=>u.CategoryId).FirstOrDefault(u=>u.Id==id);
        //    if(toy == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(toy);

        //}

        public IActionResult Delete(int? id)
        {
            //Находим объект в базе данных
            Toy toy = _db.toys.Find(id);
            if(toy == null) {
                return NotFound();
            }
            string upload = _webHostEnviroment.WebRootPath + WC.ImagePath;
            var oldImage = Path.Combine(upload, toy.Image);
            if (System.IO.File.Exists(oldImage))
            {
                //удаляем изображение
                System.IO.File.Delete(oldImage);
            }
            //удаляем обхект 
            _db.toys.Remove(toy);
            //сохраняем изменения
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Mark/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mark</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mark.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mark</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
@*                    <partial name="_LoginPartial" />*@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Toy" asp-action="Index">Toy</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>
                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>
                    </ul>
                    @if (WC.userd is null)
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Sing In</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Edit_User">@WC.userd.Name</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mark - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mark/Views/Shared/_ToyCard.cshtml
@model Mark.Models.Toy

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ','_')">
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@Model.Price</span></label></div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3"src="@WC.ImagePath@Model.Image" alt="Card img cap" />
        <div class="card-body p-1 px-3 row">
            <div class="col-8">
                <span class="badge p-2 border w-100" style="background-color:lavenderblush"> @Model.Category.Name </span>
            </div>
            <div class="col-12 pt-2" style="front-size:13px; text-align:justify">
                <p> @Model.shortDesc </p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">Description</a>
            </div>
        </div>
    </div>
</div>